'use strict';
const $=id=>document.getElementById(id), txt=(id,s)=>$(id).textContent=s;
let selected={id:292223,name:'迪拜',latitude:25.07725,longitude:55.30927,country_code:'AE',country:'阿拉伯联合酋长国',admin1:'Dubai',timezone:'Asia/Dubai',population:3790000},map,marker,selection=0,searchSeq=0,fxSeq=0,rate=null;
const countryData=fetch('countries.json').then(r=>{if(!r.ok)throw Error('国家数据暂不可用');return r.json()});countryData.catch(()=>{});
const economySnapshot=fetch('economics.json').then(r=>r.json());
const currencyData=fetch('currencies.json').then(r=>r.json());
async function json(url){const r=await fetch(url,{signal:AbortSignal.timeout(18000)});if(!r.ok)throw Error('数据服务暂不可用');return r.json()}
let worldLayer,streetLayer;
const worldData=fetch('world.json').then(r=>{if(!r.ok)throw Error('地图数据加载失败');return r.json()});worldData.catch(()=>{});
function countryStyle(feature){return{color:'#528461',weight:.8,fillColor:feature.properties.code===selected.country_code?'#386b48':'#182b20',fillOpacity:1};}
function mapMessage(value){txt('mapStatus',value);}
async function initMap(){if(!window.L){txt('map','地图组件加载失败，请重新打开文件。');return}map=L.map('map',{zoomControl:false,minZoom:2,maxZoom:18,maxBounds:[[-85,-180],[85,180]],maxBoundsViscosity:.8}).setView([24,30],2);L.control.zoom({position:'topleft'}).addTo(map);map.attributionControl.addAttribution('<a href="https://www.naturalearthdata.com/">Natural Earth</a>');try{const data=await worldData;worldLayer=L.geoJSON(data,{style:countryStyle,onEachFeature:(f,l)=>{const t=document.createElement('span');t.textContent=f.properties.name;l.bindTooltip(t)}}).addTo(map);if(marker)marker.bringToFront();mapMessage('内置世界概览 · 可缩放定位，不含街道细节');}catch{mapMessage('内置地图加载失败，请重新下载完整网页。');}const street=$('streetMap');if(location.protocol==='file:'){street.disabled=true;street.title='本地 HTML 使用内置地图；街道图需通过网页网址打开。';}street.onchange=()=>{if(!street.checked){if(worldLayer)worldLayer.addTo(map);if(streetLayer){streetLayer.off();streetLayer.remove();streetLayer=null;}mapMessage('内置世界概览 · 不含街道细节');return}if(worldLayer)worldLayer.remove();let failed=false;streetLayer=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'});streetLayer.on('tileerror',()=>{if(failed)return;failed=true;const layer=streetLayer;if(layer){layer.off();layer.remove();streetLayer=null;}street.checked=false;if(worldLayer)worldLayer.addTo(map);if(marker)marker.bringToFront();mapMessage('街道服务暂不可用，已恢复内置世界概览。');});streetLayer.addTo(map);mapMessage('在线街道图 · OpenStreetMap');};}

function offset(zone,date){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(date);const p=Object.fromEntries(parts.map(x=>[x.type,x.value]));return (Date.UTC(+p.year,+p.month-1,+p.day,+p.hour,+p.minute,+p.second)-Math.floor(date.getTime()/1000)*1000)/3600000;}
function overlapWindows(zone,now){const start=new Date(now);start.setTime(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate())-8*3600000);const beijingDate=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(now);while(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(start)!==beijingDate)start.setTime(start.getTime()+86400000);const blocks=[];let opened=null;for(let minute=540;minute<=1200;minute+=15){const t=new Date(start.getTime()+minute*60000);const p=Object.fromEntries(new Intl.DateTimeFormat('en',{timeZone:zone,weekday:'short',hour:'numeric',minute:'numeric',hourCycle:'h23'}).formatToParts(t).map(x=>[x.type,x.value]));const on=minute<1200&&!['Sat','Sun'].includes(p.weekday)&&+p.hour>=9&&+p.hour<18;if(on&&opened===null)opened=minute;if(!on&&opened!==null){blocks.push([opened,minute]);opened=null}}return blocks;}
function setViewMode(mode){if(!map)return;document.querySelectorAll('.mapviews button').forEach(b=>b.setAttribute('aria-pressed',String(b.id===mode)));map.flyTo(mode==='world'?[22,15]:[selected.latitude,selected.longitude],mode==='world'?2:mode==='region'?(selected.isCountry?countryZoom(selected.area):4):(selected.isCountry?countryZoom(selected.area):10));}
function regionDescription(c){return [c.country,c.name].filter(Boolean).join(' / ')+' · '+(c.latitude>=0?'北半球':'南半球')+' · '+(c.longitude>=0?'东半球':'西半球');}
function updateClock(){const now=new Date(),zone=selected.timezone;txt('chinaTime',new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(now));if(selected.isCountry){txt('localTime','—');txt('localDate','国家 / 地区概览');txt('difference','请选择客户所在城市');txt('workStatus','待选择城市');txt('contact','国家可能跨越多个时区。请搜索具体城市，查看客户当地时间。');txt('overlap','选择城市后计算');txt('channelHint','国家经济与报价换算仍可使用。');$('hours').replaceChildren();return}if(!zone){['localTime','localDate','difference','contact','workStatus','overlap'].forEach(id=>txt(id,'时区数据缺失'));txt('channelHint','');$('hours').replaceChildren();return}txt('localTime',new Intl.DateTimeFormat('zh-CN',{timeZone:zone,hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(now));txt('localDate',new Intl.DateTimeFormat('zh-CN',{timeZone:zone,month:'short',day:'numeric',weekday:'short'}).format(now));const diff=offset(zone,now)-offset('Asia/Shanghai',now);txt('difference',diff===0?'与北京时间相同':'比北京'+(diff>0?'快':'慢')+' '+Math.abs(diff)+' 小时');const h=Number(new Intl.DateTimeFormat('en',{timeZone:zone,hour:'numeric',hourCycle:'h23'}).format(now)),day=new Intl.DateTimeFormat('en',{timeZone:zone,weekday:'short'}).format(now),weekend=['Sat','Sun'].includes(day),work=!weekend&&h>=9&&h<18;const b=Number(new Intl.DateTimeFormat('en',{timeZone:'Asia/Shanghai',hour:'numeric',hourCycle:'h23'}).format(now)),both=work&&b>=9&&b<20;txt('workStatus',both?'双方工作时段':work?'客户工作时段':weekend?'客户当地周末':'客户非工作时段');txt('contact',both?'适合用 WhatsApp 沟通项目需求。':work?'客户处于常规工作时段，你的工作时段已结束。':'客户可能正在休息，暂未回复不一定代表没有意向。');const hh=m=>String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0');const windows=overlapWindows(zone,now);txt('overlap',windows.length?windows.map(([a,b])=>hh(a)+'–'+hh(b)).join(' / '):'今天无重叠时段');txt('channelHint',windows.length?'今天可优先在交集时段用 WhatsApp 跟进；详细资料可通过邮件发送。':'可先准备邮件，选择客户下一个工作时段发送。');$('hours').replaceChildren(...Array.from({length:24},(_,i)=>{const el=document.createElement('i');el.className=(i>=9&&i<18?'active ':'')+(i===h?'now':'');return el}));}

const indicators=[['人均 GDP','NY.GDP.PCAP.CD','美元'],['国家人口','SP.POP.TOTL','人'],['人均 GDP · PPP','NY.GDP.PCAP.PP.CD','国际元'],['GDP 年增长','NY.GDP.MKTP.KD.ZG','%']];
function format(v,unit){if(unit==='%')return v.toFixed(1)+'%';if(unit==='人')return v>=1e8?(v/1e8).toFixed(2)+' 亿':v>=1e4?(v/1e4).toFixed(1)+' 万':v.toLocaleString('zh-CN');return Math.round(v).toLocaleString('zh-CN')}
async function economics(c,seq){let gdp=null;$('metrics').replaceChildren(...indicators.map(([name])=>{let el=document.createElement('div');el.className='metric';let label=document.createElement('label');label.textContent=name;let value=document.createElement('strong');value.textContent='读取中…';let meta=document.createElement('small');meta.textContent='世界银行';el.append(label,value,meta);return el}));await Promise.all(indicators.map(async([name,code,unit],i)=>{let row;try{const snapshot=await economySnapshot;row=snapshot.indicators[code]?.[1]?.find(x=>x.country.id===c.country_code&&x.value!==null)}catch{}if(seq!==selection)return;let cell=$('metrics').children[i];cell.querySelector('strong').textContent=row?format(row.value,unit):'暂无数据';cell.querySelector('small').textContent=row?`${row.date} 年 · ${unit}`:'来源未提供或暂不可用';if(i===0)gdp=row?.value}));if(seq!==selection)return;}
async function exchange(){const seq=++fxSeq;rate=null;txt('converted','读取中…');txt('rateInfo','');const quote=$('currency').value,base=$('baseCurrency').value;txt('quoteCurrency',quote);if(!quote){txt('converted','暂无数据');return}try{let d=quote===base?{rate:1,date:new Date().toISOString().slice(0,10)}:await json(`https://api.frankfurter.dev/v2/rate/${base}/${encodeURIComponent(quote)}`);if(seq!==fxSeq)return;if(!Number.isFinite(d.rate))throw Error();rate=d.rate;txt('rateInfo',`1 ${base} ≈ ${rate.toLocaleString('zh-CN',{maximumFractionDigits:6})} ${quote} · ${d.date} · 参考价`);convert()}catch{if(seq!==fxSeq)return;txt('converted','暂无汇率');txt('rateInfo','该货币暂无报价，或数据服务暂不可用。可重新选择货币重试。')}}
function convert(){if(rate===null)return;const n=Number($('amount').value);txt('converted',$('amount').value===''||!Number.isFinite(n)||n<0?'请输入有效金额':(n*rate).toLocaleString('zh-CN',{maximumFractionDigits:2}));}
async function selectCity(c){const seq=++selection;++fxSeq;selected=c;if(worldLayer)worldLayer.setStyle(countryStyle);rate=null;$('results').replaceChildren();txt('city',c.name);txt('country',c.isCountry?'国家 / 地区 · '+c.english:[c.country,c.admin1].filter(Boolean).join(' · '));$('cityView').disabled=!!c.isCountry;txt('mapLabel',c.isCountry?c.name+' · 国家 / 地区概览':`${c.name} · ${c.country||c.country_code}`);txt('coordinates',`${c.isCountry?'国家参考坐标 · ':''}${Math.abs(c.latitude).toFixed(4)}° ${c.latitude>=0?'N':'S'} · ${Math.abs(c.longitude).toFixed(4)}° ${c.longitude>=0?'E':'W'}`);txt('cityPopulation',`城市人口：${c.population?format(c.population,'人')+' 人（GeoNames，未提供统计年份）':'暂无数据'}。货币映射：Unicode CLDR，下载于 2026-09-15。`);if(c.isCountry)txt('cityPopulation','国家地理信息来自 mledoze/countries（ODbL），获取于 2026-09-16。地图点为国家参考坐标，不是客户地址；人口请参考国家人口指标。');if(map){if(marker)marker.remove();marker=L.circleMarker([c.latitude,c.longitude],{radius:9,color:'#fff',weight:3,fillColor:'#83ffb1',fillOpacity:1}).addTo(map);const label=document.createElement('span');label.textContent=c.name;marker.bindTooltip(label,{permanent:true,direction:'top',offset:[0,-10]});map.flyTo([c.latitude,c.longitude],c.isCountry?countryZoom(c.area):4,{duration:1.3});}document.querySelectorAll('.mapviews button').forEach(b=>b.setAttribute('aria-pressed',String(b.id==='region')));txt('geography',c.isCountry?[({Asia:'亚洲',Europe:'欧洲',Africa:'非洲',Americas:'美洲',Oceania:'大洋洲',Antarctic:'南极洲'})[c.region]||c.region,c.name].filter(Boolean).join(' / '):regionDescription(c));updateClock();void economics(c,seq);txt('converted','读取中…');txt('rateInfo','');try{const all=await currencyData;if(seq!==selection)return;const today=new Date().toISOString().slice(0,10);const list=(all[c.country_code]||[]).flatMap(x=>Object.entries(x).filter(([,v])=>v._tender!=='false'&&(!v._to||v._to>=today)&&(!v._from||v._from<=today)).map(([k])=>k));const codes=[...new Set([...list,'USD','EUR','CNY'])];$('currency').replaceChildren(...codes.map(k=>{let o=document.createElement('option');o.value=k;o.textContent=k+(list.includes(k)?' · 当地货币':'');return o}));await exchange();}catch{if(seq===selection){txt('converted','暂无数据');txt('rateInfo','货币信息加载失败，请刷新重试。')}}}
function countryZoom(area){return area>5000000?2:area>1000000?3:area>200000?4:area>10000?5:7;}
function normalizePlace(s){let t=String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[.\s_-]/g,'');return window.OpenCC?OpenCC.Converter({from:'tw',to:'cn'})(t):t;}
function matchCountries(all,q){const n=normalizePlace(q),zh=new Intl.DisplayNames(['zh-CN'],{type:'region'});const aliases={US:['美国','美國','美利坚','USA','U.S.A.'],GB:['英国','英國','UK','Britain','Great Britain'],AE:['阿联酋','阿聯酋','UAE'],KR:['韩国','韓國','South Korea'],RU:['俄罗斯','俄羅斯'],SA:['沙特','沙特阿拉伯'],VN:['越南'],CZ:['捷克','Czech Republic']};return all.map(c=>{const name=zh.of(c.cca2)||c.translations?.zho?.common||c.name.common;const names=[name,c.name.common,c.name.official,c.translations?.zho?.common,c.translations?.zho?.official,c.cca2,c.cca3,...(c.altSpellings||[]),...(aliases[c.cca2]||[])].filter(Boolean).map(normalizePlace);const rank=names.includes(n)?0:names.some(x=>x.startsWith(n)&&x.length>3)?1:n.length>=3&&names.some(x=>x.includes(n))?2:9;return{rank,id:'country-'+c.cca2,isCountry:true,name,english:c.name.common,country:name,country_code:c.cca2,latitude:c.latlng?.[0],longitude:c.latlng?.[1],area:c.area,region:c.region}}).filter(c=>c.rank<9&&Number.isFinite(c.latitude)&&Number.isFinite(c.longitude)).sort((a,b)=>a.rank-b.rank).slice(0,15);}
function renderPlaces(rows){$('results').replaceChildren(...rows.map(c=>{const b=document.createElement('button');b.className='result';const n=document.createElement('span');n.textContent=c.name;const m=document.createElement('small');m.textContent=c.isCountry?'国家 / 地区 · '+c.english:'城市 · '+[c.country,c.admin1,c.admin2].filter(Boolean).join(' · ');b.append(n,m);b.onclick=()=>{++searchSeq;txt('searchStatus','已定位：'+c.name+' · '+(c.isCountry?'国家 / 地区':c.country||c.country_code));void selectCity(c)};return b}));}
async function searchCities(query){const q=query.trim();if(q.length<2)throw Error('请输入至少两个字符');const seq=++searchSeq;txt('searchStatus','正在查找国家和城市…');$('results').replaceChildren();let countries=[],countryFailed=false;try{countries=matchCountries(await countryData,q)}catch{countryFailed=true}if(seq!==searchSeq)return[];if(countries.length){renderPlaces(countries);txt('searchStatus','找到 '+countries.length+' 个国家 / 地区，可直接选择；继续查询城市…')}const traditional=window.OpenCC?OpenCC.Converter({from:'cn',to:'tw'})(q):q;const terms=[...new Set([q,traditional])];const response=await Promise.allSettled(terms.map(term=>json('https://geocoding-api.open-meteo.com/v1/search?name='+encodeURIComponent(term)+'&count=12&language=zh&format=json')));if(seq!==searchSeq)return[];const cities=[...new Map(response.flatMap(r=>r.status==='fulfilled'?(r.value.results||[]):[]).filter(x=>x.feature_code?.startsWith('PPL')).map(x=>[x.id,x])).values()].sort((a,b)=>(b.population||0)-(a.population||0));const rows=[...countries,...cities],cityFailed=response.every(r=>r.status==='rejected');renderPlaces(rows);txt('searchStatus',rows.length?'找到 '+countries.length+' 个国家 / 地区、'+cities.length+' 个城市，请选择。'+(cityFailed?'城市服务暂不可用，可重试。':'')+(countryFailed?'国家数据暂不可用，请刷新重试。':''):cityFailed||countryFailed?'部分查询服务暂不可用，请稍后重试。':'没有找到匹配。请尝试国家或城市的中英文名，例如 美国 / Germany / Dubai。');return rows.map(c=>({id:c.id,name:c.name,type:c.isCountry?'country':'city',country:c.country,region:c.admin1}));}

$('search').onsubmit=e=>{e.preventDefault();void searchCities($('query').value)};document.querySelectorAll('[data-city]').forEach(b=>b.onclick=()=>{$('query').value=b.dataset.city;void searchCities(b.dataset.city)});$('world').onclick=()=>setViewMode('world');$('region').onclick=()=>setViewMode('region');$('cityView').onclick=()=>setViewMode('cityView');$('currency').onchange=exchange;$('amount').oninput=convert;$('baseCurrency').onchange=exchange;initMap();void selectCity(selected);setInterval(updateClock,1000);
if(document.modelContext?.registerTool){const controller=new AbortController();window.addEventListener('pagehide',()=>controller.abort(),{once:true});try{Promise.resolve(document.modelContext.registerTool({name:'search_cities',description:'按中英文国家或城市名查询，在页面展示带类型标记的国家和城市结果。',inputSchema:{type:'object',properties:{query:{type:'string',minLength:2}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async input=>{if(typeof input?.query!=='string'||input.query.trim().length<2)throw Error('城市名称至少需要两个字符');$('query').value=input.query;return{cities:await searchCities(input.query)}}},{signal:controller.signal})).catch(()=>{})}catch{}}
